//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatroskaBatchToolBox.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatroskaBatchToolBox.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyRunnningMessasgeText {
            get {
                return ResourceManager.GetString("AlreadyRunnningMessasgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start normalizing the audio of the movie file. Press [q] to abort. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioNormalizationProcessStartMessageText {
            get {
                return ResourceManager.GetString("AudioNormalizationProcessStartMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}-{1:D2}-{2:D2} {3:D2}:{4:D2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletionDateTimeFriendlyFormat1Text {
            get {
                return ResourceManager.GetString("CompletionDateTimeFriendlyFormat1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}-{1:D2} {2:D2}:{3:D2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletionDateTimeFriendlyFormat2Text {
            get {
                return ResourceManager.GetString("CompletionDateTimeFriendlyFormat2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}:{1:D2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletionDateTimeFriendlyFormat3Text {
            get {
                return ResourceManager.GetString("CompletionDateTimeFriendlyFormat3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion process finished. Press ENTER to exit the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessCompletedMessageText {
            get {
                return ResourceManager.GetString("ProcessCompletedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% completed. elapsed {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressFormat1Text {
            get {
                return ResourceManager.GetString("ProgressFormat1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% completed. elapsed {1}, remain {2}, until around {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressFormat2Text {
            get {
                return ResourceManager.GetString("ProgressFormat2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [q] key was pressed. Please wait a moment while the conversion process is interrupted... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q_KeyPressedMessasgeText {
            get {
                return ResourceManager.GetString("Q_KeyPressedMessasgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}d {1:D2}h {2:D2}m に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeSpanFriendlyFormat1Text {
            get {
                return ResourceManager.GetString("TimeSpanFriendlyFormat1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}h {1:D2}m に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeSpanFriendlyFormat2Text {
            get {
                return ResourceManager.GetString("TimeSpanFriendlyFormat2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}m に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeSpanFriendlyFormat3Text {
            get {
                return ResourceManager.GetString("TimeSpanFriendlyFormat3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (&lt; 1 minute) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeSpanFriendlyFormat4Text {
            get {
                return ResourceManager.GetString("TimeSpanFriendlyFormat4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start video conversion of movie file or conversion to Matroska format (&quot;.mkv&quot;). Press the [q] key to abort. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VideoConversionStartMessageText {
            get {
                return ResourceManager.GetString("VideoConversionStartMessageText", resourceCulture);
            }
        }
    }
}
